require_relative 'helper'

class ComponentTest < PryTest::Test

  before do
    @page = Capybara::Session.new(:poltergeist, TestApp)
  end

  test 'render' do
    @page.visit '/'
    assert @page.html['head']
    assert @page.html["Generated by Opal"]
  end

  test 'tmpl' do
    @page.visit '/box'
    # box div should not be in the html as it's a tmpl (template)
    assert !@page.html['Hello, Box!']
    # clicking the show link should show the box div and remove the show link
    @page.click_link 'Show'
    assert @page.html['Hello, Box!']
    assert !@page.html['Show']
  end

  after { Capybara.reset_sessions! }
end
