require_relative 'helper'

class ComponentTest < PryTest::Test

  before { @page = Capybara::Session.new(:poltergeist, TestApp) }

  test 'render' do
    @page.visit '/'
    assert @page.html['head']
    assert @page.html["Generated by Opal"]
  end

  test 'tmpl' do
    @page.visit '/theme'
    # Make sure the about title isn't there
    assert !@page.html['"about-title"']
    # Clicking the link should show the about title
    @page.click_link 'Show About Title'
    # Remove the link from the dom after it's clicked
    assert !@page.html['Show About Title']
    # Should see the title
    assert @page.html['"about-title"']
  end

  after { Capybara.reset_sessions! }
end
